# -*- makefile-gmake -*-

################################
## Package code configuration ##
################################

.PHONY: announce version configure

version:
	@ echo "let number = \"$(VERSION)\"" > src/version.ml

configure: version
	@ sh check-dependencies.sh
